### ISSUE TITLE
TypeError: Cannot read property 'fetch' of undefined

### ISSUE THREAD

**Issue by Arbolista** [expo/jest-expo#13]
When running tests, I receive the following error with this jest preset:

```
npm t

 FAIL  __tests__/index.ios.js
  ● Test suite failed to run

    TypeError: Cannot read property 'fetch' of undefined
      
      at node_modules/whatwg-fetch/fetch.js:4:8
      at Object.<anonymous> (node_modules/whatwg-fetch/fetch.js:461:3)
      at Object.<anonymous> (node_modules/jest-expo/src/setup.js:94:397)
```

I am currently using expo to get default locale for i18next:

```
import i18n from 'i18next';
import Expo from 'expo';
import en from './locales/en';
import es from './locales/es';


// creating a language detection plugin using expo
// http://i18next.com/docs/ownplugin/#languagedetector
const languageDetector = {
  type: 'languageDetector',
  async: true, // flags below detection to be async
  detect: (callback => Expo.Util.getCurrentLocaleAsync().then((lng) => { callback(lng); })),
  init: () => {},
  cacheUserLanguage: () => {}
};
```

package.json:

```
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "clean": "rm -fr $TMPDIR/react-* && watchman watch-del-all",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "lint": "eslint . --fix"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [],
    "setupFiles": [
      "./__tests__/setup.js"
    ]
  },
  "dependencies": {
    "babel-preset-latest": "^6.24.1",
    "color": "^2.0.0",
    "eslint": "^3.19.0",
    "expo": "^18.0.6",
    "i18next": "^8.4.3",
    "json-schema-parser": "^0.1.0",
    "jsonschema": "^1.1.1",
    "lodash": "^4.17.4",
    "native-base": "^2.2.0",
    "prop-types": "^15.5.10",
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-vector-icons": "^4.2.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.1",
    "redux-act": "^1.3.0",
    "redux-catch": "^1.3.1",
    "redux-observable": "^0.14.1",
    "redux-reset": "^0.3.0",
    "redux-storage": "^4.1.2",
    "redux-storage-decorator-debounce": "^1.1.3",
    "redux-storage-decorator-filter": "^1.1.8",
    "redux-storage-engine-reactnativeasyncstorage": "^1.0.5",
    "rxjs": "^5.4.1",
    "tcomb-form-native": "^0.6.9"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-core": "^6.25.0",
    "babel-eslint": "^7.2.3",
    "babel-jest": "^20.0.3",
    "babel-plugin-module-resolver": "^2.7.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react-native": "2.0.0",
    "chai": "^4.0.2",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-import-resolver-babel-module": "^3.0.0",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.0.1",
    "flow": "^0.2.3",
    "jest": "^20.0.4",
    "jest-cli": "^20.0.4",
    "jest-expo": "^18.0.0",
    "mocha": "^3.4.2",
    "react-test-renderer": "^16.0.0-alpha.12",
    "reactotron-react-native": "^1.12.0",
    "reactotron-redux": "^1.12.0",
    "regenerator-runtime": "^0.10.5",
    "whatwg-fetch": "^2.0.3"
  }
}
```

Let me know if there is any other info I can provide.

**Comment by Arbolista** [comment]
**Update**
I actually can replicate this with the `react-native` preset, so it's not a `jext-expo` issue.

**Comment by Philip-Nunoo** [comment]
@erichulburd would be helpful to describe how you were able to solve this issue. Facing similar problem here.

**Comment by maitham1** [comment]
@Philip-Nunoo  did you manage to fix this
