### ISSUE TITLE
Fails to import 'expo'

### ISSUE THREAD

**Issue by amasad** [expo/jest-expo#9]
Fails to `import 'expo'` in tests with the following error:

```
    ReferenceError: window is not defined
      
      at Object.<anonymous> (node_modules/expo/src/Location.js:199:1)
      at Object.<anonymous> (fail-test.js:1:90)
```

Here is a repo to demonstrate the issue: https://github.com/amasad/jest-expo-mock

**Comment by skevy** [comment]
Hey @amasad just wanted to let you know I haven't forgotten about this -- just haven't had time to dig in and fix yet. It's a bit of a project to mock all of our JS modules for you automatically. Will update here soon.
